# Automatically generated variables for the Jinja template

text_variables = {
    'txt_1': 'Jesus Torrejon - Portfolio',
    'txt_2': 'Home',
    'txt_3': 'About me',
    'txt_4': 'Resume',
    'txt_5': 'Personal projects',
    'txt_6': 'Socials',
    'txt_7': 'Home',
    'txt_8': 'About Me',
    'txt_9': 'Resume',
    'txt_10': 'Portfolio',
    'txt_11': 'Socials',
    'txt_12': 'Jesus Torrejon',
    'txt_13': 'Software Developer',
    'txt_14': 'AI Enthusiast',
    'txt_15': 'Solutions Designer',
    'txt_16': 'About me',
    'txt_17': 'My Professional Role',
    'txt_18': 'Enterprise Software Development',
    'txt_19': 'Engineering enterprise microservices for scalability, security, and audit compliance.',
    'txt_20': 'Cloud Systems Deployment',
    'txt_21': 'Skilled at deploying container-based systems equipped with automated CI/CD pipelines, ensuring\n                    seamless scaling and efficient operations.',
    'txt_22': 'Systems Integration',
    'txt_23': 'Expertise in interpreting external specifications to craft integrated solutions, with rigorous\n                    testing validating every new connection.',
    'txt_24': 'My career',
    'txt_25': 'Resume',
    'txt_26': 'Education and Training',
    'txt_27': 'B.S. Computer Science',
    'txt_28': 'National Univesity of engineering',
    'txt_29': 'I graduated in 2022 with a Bachelor’s degree in Computer Science from the National\n                                University of Engineering (UNI-Peru), where the program focuses on programming and\n                                artificial intelligence. The curriculum is designed to develop strong skills in software\n                                development, machine learning, and computer graphics.',
    'txt_30': 'During my studies, I\n                                achieved notable academic distinctions. I secured first place in the Faculty of Science\n                                entrance exam in 2017, ranking first among 80 admitted students. Consistently\n                                maintaining high academic standards to retain my Pronabec scholarship, I ranked within\n                                the top 20% of my class and earned second place among all students in the Faculty of\n                                Science during my ninth semester.',
    'txt_31': 'Job Experience',
    'txt_32': 'Xcale Tech',
    'txt_33': 'Backend developer',
    'txt_34': "As a Java backend developer, I actively contributed to Nuba's internal management\n                                system, built on over 10 microservices using Java/Spring Boot, and designed under the\n                                Backend For Frontend (BFF) pattern to support multiple portals.",
    'txt_35': 'Developed data registration features focused on REST APIs with PostgreSQL, utilizing\n                                  a hexagonal architecture.',
    'txt_36': 'Resolved deployment pipeline issues using AWS CodePipeline and monitoring with\n                                  CloudWatch, connecting multiple databases and services across various environments.',
    'txt_37': 'Integrated notification services with Firebase to ensure real-time updates on data\n                                  changes.',
    'txt_38': 'Visiva: Toulouse Lautrec',
    'txt_39': 'Backend developer',
    'txt_40': 'I was a key backend developer for the mobile application Toulouse+, used by over 1,000\n                                students.',
    'txt_41': 'Developed REST API services in Spring Boot to support the functionality of the\n                                  mobile application.',
    'txt_42': 'Created a Notification Service integrating Firebase Cloud Messaging for event-based\n                                  notifications.',
    'txt_43': 'Designed a Content Service to display data from a MySQL database and an Information\n                                  Service integrated with PeopleSoft using Oracle SQL.',
    'txt_44': 'BigData/HPC Lab CTIC-UNI',
    'txt_45': 'IOT Software developer',
    'txt_46': 'Developed a Raspberry Pi device for public transport management, focusing on GPS\n                                  tracking and passenger control.',
    'txt_47': 'Implemented multi-threaded Python software for efficient GPS data processing and\n                                  backend communication.',
    'txt_48': 'Featured Work',
    'txt_49': 'Personal Projects',
    'txt_50': 'Desktop App',
    'txt_51': '360 Video Player',
    'txt_52': '360 Video Player is a local video player for 360 video. Simply drag your video file into the player\n                    to instantly immerse yourself in a 360-degree experience, all from the comfort of your own device.',
    'txt_53': 'Web Application',
    'txt_54': 'YT-no-cookie',
    'txt_55': 'YT-No-Cookie Viewer is a minimalist web interface designed to help you watch YouTube videos with\n                    fewer distractions.',
    'txt_56': 'Desktop App',
    'txt_57': 'SpaceGrid',
    'txt_58': 'OpenGL/C++ game where you control a spaceship moving on a grid!',
}

link_variables = {
    'link_1': 'index.html',
    'link_2': '#home',
    'link_3': '#about',
    'link_4': '#resume',
    'link_5': '#portfolio',
    'link_6': 'https://www.linkedin.com/in/jes%C3%BAs-andr%C3%A9s-torrej%C3%B3n-le%C3%B3n-511351190/',
    'link_7': 'https://github.com/thehancode',
    'link_8': 'https://x.com/jesucode',
    'link_9': 'index.html',
    'link_10': 'index.html',
    'link_11': '#home',
    'link_12': '#about',
    'link_13': '#resume',
    'link_14': '#portfolio',
    'link_15': 'https://www.linkedin.com/in/jes%C3%BAs-andr%C3%A9s-torrej%C3%B3n-le%C3%B3n-511351190/',
    'link_16': 'https://github.com/thehancode',
    'link_17': 'https://x.com/jesucode',
    'link_18': 'https://github.com/thehancode/360-video-player',
    'link_19': 'https://github.com/thehancode/360-video-player',
    'link_20': 'https://github.com/thehancode/360-video-player',
    'link_21': '#',
    'link_22': 'https://github.com/thehancode/no-cookie-viewer',
    'link_23': 'https://github.com/thehancode/no-cookie-viewer',
    'link_24': 'https://github.com/thehancode/no-cookie-viewer',
    'link_25': '#',
    'link_26': 'https://github.com/thehancode/SpaceGrid',
    'link_27': 'https://github.com/thehancode/SpaceGrid',
    'link_28': 'https://github.com/thehancode/SpaceGrid',
}

image_variables = {
    'img_1': 'assets/images/logo/logo-06.png',
    'img_2': 'assets/images/logo/logo.png',
    'img_3': 'assets/images/logo/logos-circle.png',
    'img_4': 'assets/images/slider/banner-06.png',
    'img_5': 'assets/images/portfolio/portfolio-01.gif',
    'img_6': 'assets/images/portfolio/portfolio-02.jpg',
    'img_7': 'assets/images/portfolio/portfolio-03.png',
}

links_variables = {
    'link_1': 'assets/images/favicon.ico',
    'link_2': 'assets/css/vendor/bootstrap.min.css',
    'link_3': 'assets/css/vendor/slick.css',
    'link_4': 'assets/css/vendor/slick-theme.css',
    'link_5': 'assets/css/vendor/aos.css',
    'link_6': 'assets/css/plugins/feature.css',
    'link_7': 'assets/css/style.css',
    'link_8': 'style.css',
}

script_variables = {
    'script_1': 'assets/js/vendor/jquery.js',
    'script_2': 'assets/js/vendor/modernizer.min.js',
    'script_3': 'assets/js/vendor/feather.min.js',
    'script_4': 'assets/js/vendor/slick.min.js',
    'script_5': 'assets/js/vendor/bootstrap.js',
    'script_6': 'assets/js/vendor/text-type.js',
    'script_7': 'assets/js/vendor/wow.js',
    'script_8': 'assets/js/vendor/aos.js',
    'script_9': 'assets/js/vendor/particles.js',
    'script_10': 'assets/js/main.js',
    'script_11': 'script.js',
}

