# Automatically generated variables for the Jinja template

text_variables = {
    'txt_1': 'Jesus Torrejon - Portfolio',
    'txt_2': 'Home',
    'txt_3': 'About me',
    'txt_4': 'Personal projects',
    'txt_5': 'Socials',
    'txt_6': 'Home',
    'txt_7': 'About Me',
    'txt_8': 'Portfolio',
    'txt_9': 'Socials',
    'txt_10': 'Jesus Torrejon',
    'txt_11': 'Software Developer',
    'txt_12': 'AI Enthusiast',
    'txt_13': 'Solutions Designer',
    'txt_14': 'About me',
    'txt_15': 'My Professional Role',
    'txt_16': 'Enterprise Software Development',
    'txt_17': 'Engineering enterprise microservices for scalability, security, and audit compliance.',
    'txt_18': 'Cloud Systems Deployment',
    'txt_19': 'Skilled at deploying container-based systems equipped with automated CI/CD pipelines, ensuring\n                    seamless scaling and efficient operations.',
    'txt_20': 'Systems Integration',
    'txt_21': 'Expertise in interpreting external specifications to craft integrated solutions, with rigorous\n                    testing validating every new connection.',
    'txt_22': 'Featured Work',
    'txt_23': 'Personal Projects',
    'txt_24': 'Desktop App',
    'txt_25': '360 Video Player',
    'txt_26': '360 Video Player is a local video player for 360 video. Simply drag your video file into the player\n                    to instantly immerse yourself in a 360-degree experience, all from the comfort of your own device.',
    'txt_27': 'Web Application',
    'txt_28': 'YT-no-cookie',
    'txt_29': 'YT-No-Cookie Viewer is a minimalist web interface designed to help you watch YouTube videos with\n                    fewer distractions.',
    'txt_30': 'Desktop App',
    'txt_31': 'SpaceGrid',
    'txt_32': 'OpenGL/C++ game where you control a spaceship moving on a grid!',
}

link_variables = {
    'link_1': 'index.html',
    'link_2': '#home',
    'link_3': '#about',
    'link_4': '#portfolio',
    'link_5': 'https://www.linkedin.com/in/jes%C3%BAs-andr%C3%A9s-torrej%C3%B3n-le%C3%B3n-511351190/',
    'link_6': 'https://github.com/thehancode',
    'link_7': 'https://x.com/jesucode',
    'link_8': 'index.html',
    'link_9': 'index.html',
    'link_10': '#home',
    'link_11': '#about',
    'link_12': '#portfolio',
    'link_13': 'https://www.linkedin.com/in/jes%C3%BAs-andr%C3%A9s-torrej%C3%B3n-le%C3%B3n-511351190/',
    'link_14': 'https://github.com/thehancode',
    'link_15': 'https://x.com/jesucode',
    'link_16': 'https://github.com/thehancode/360-video-player',
    'link_17': 'https://github.com/thehancode/360-video-player',
    'link_18': 'https://github.com/thehancode/360-video-player',
    'link_19': '#',
    'link_20': 'https://github.com/thehancode/no-cookie-viewer',
    'link_21': 'https://github.com/thehancode/no-cookie-viewer',
    'link_22': 'https://github.com/thehancode/no-cookie-viewer',
    'link_23': '#',
    'link_24': 'https://github.com/thehancode/SpaceGrid',
    'link_25': 'https://github.com/thehancode/SpaceGrid',
    'link_26': 'https://github.com/thehancode/SpaceGrid',
}

image_variables = {
    'img_1': 'assets/images/logo/logo-06.png',
    'img_2': 'assets/images/logo/logo.png',
    'img_3': 'assets/images/logo/logos-circle.png',
    'img_4': 'assets/images/slider/banner-06.png',
    'img_5': 'assets/images/portfolio/portfolio-01.gif',
    'img_6': 'assets/images/portfolio/portfolio-02.jpg',
    'img_7': 'assets/images/portfolio/portfolio-03.png',
}

links_variables = {
    'links_1': 'assets/images/favicon.ico',
    'links_2': 'assets/css/vendor/bootstrap.min.css',
    'links_3': 'assets/css/vendor/slick.css',
    'links_4': 'assets/css/vendor/slick-theme.css',
    'links_5': 'assets/css/vendor/aos.css',
    'links_6': 'assets/css/plugins/feature.css',
    'links_7': 'assets/css/style.css',
    'links_8': 'style.css',
}

script_variables = {
    'script_1': 'assets/js/vendor/jquery.js',
    'script_2': 'assets/js/vendor/modernizer.min.js',
    'script_3': 'assets/js/vendor/feather.min.js',
    'script_4': 'assets/js/vendor/slick.min.js',
    'script_5': 'assets/js/vendor/bootstrap.js',
    'script_6': 'assets/js/vendor/text-type.js',
    'script_7': 'assets/js/vendor/wow.js',
    'script_8': 'assets/js/vendor/aos.js',
    'script_9': 'assets/js/vendor/particles.js',
    'script_10': 'assets/js/main.js',
    'script_11': 'script.js',
}

