# Automatically generated variables for the Jinja template

text_variables = {
    'txt_1': 'Jesus Torrejon - Portfolio',
    'txt_2': 'Inicio',
    'txt_3': 'Acerca de mí',
    'txt_4': 'Currículum',
    'txt_5': 'Proyectos Personales',
    'txt_6': 'Redes Sociales',
    'txt_7': 'Inicio',
    'txt_8': 'Acerca de mí',
    'txt_9': 'Currículum',
    'txt_10': 'Portfolio',
    'txt_11': 'Redes Sociales',
    'txt_12': 'Jesus Torrejon',
    'txt_13': 'Software Developer',
    'txt_14': 'AI Enthusiast',
    'txt_15': 'Solutions Designer',
    'txt_16': 'Acerca de mí',
    'txt_17': 'Mi Rol Profesional',
    'txt_18': 'Desarrollo de Software Empresarial',
    'txt_19': 'Ingeniería de microservicios empresariales para escalabilidad, seguridad y cumplimiento de auditorías.',
    'txt_20': 'Despliegue de Sistemas en la Nube',
    'txt_21': 'Con experiencia en el despliegue de sistemas basados en contenedores con pipelines CI/CD automatizados, asegurando una escalabilidad fluida y operaciones eficientes.',
    'txt_22': 'Integración de Sistemas',
    'txt_23': 'Experiencia en interpretar especificaciones externas para crear soluciones integradas, con pruebas rigurosas que validan cada nueva conexión.',
    'txt_24': 'Mi carrera',
    'txt_25': 'Currículum',
    'txt_26': 'Educación y Formación',
    'txt_27': 'B.S. en Ciencias de la Computación',
    'txt_28': 'Universidad Nacional de Ingeniería',
    'txt_29': 'Me gradué en 2022 con el grado de Bachiller en Ciencias de la Computación de la Universidad Nacional de Ingeniería (UNI-Perú), donde el programa se centra en la programación y la inteligencia artificial. El plan de estudios está diseñado para desarrollar sólidas habilidades en desarrollo de software, aprendizaje automático y gráficos por computadora.',
    'txt_30': 'Durante mis estudios, obtuve notables distinciones académicas. Logré el primer puesto en el examen de ingreso de la Facultad de Ciencias en 2017, ubicándome primero entre 80 estudiantes admitidos. Al mantener altos estándares académicos para conservar mi beca Pronabec, me ubiqué dentro del 20% superior de mi clase y obtuve el segundo lugar entre todos los estudiantes de la Facultad de Ciencias durante mi noveno semestre.',
    'txt_31': 'Experiencia Laboral',
    'txt_32': 'Xcale Tech',
    'txt_33': 'Backend Developer',
    'txt_34': 'Como Java Backend Developer, contribuí activamente al sistema de gestión interno de Nuba, construido sobre más de 10 microservicios utilizando Java/Spring Boot y diseñado bajo el patrón Backend For Frontend (BFF) para dar soporte a múltiples portales.',
    'txt_35': 'Desarrollé funcionalidades de registro de datos enfocadas en REST APIs con PostgreSQL, utilizando una arquitectura hexagonal.',
    'txt_36': 'Resolví problemas en la pipeline de despliegue utilizando AWS CodePipeline y monitoreo con CloudWatch, conectando múltiples bases de datos y servicios a lo largo de varios entornos.',
    'txt_37': 'Integré servicios de notificaciones con Firebase para asegurar actualizaciones en tiempo real sobre cambios en los datos.',
    'txt_38': 'Visiva: Toulouse Lautrec',
    'txt_39': 'Backend Developer',
    'txt_40': 'Fui un desarrollador backend clave para la aplicación móvil Toulouse+, utilizada por más de 1,000 estudiantes.',
    'txt_41': 'Desarrollé servicios REST API en Spring Boot para soportar la funcionalidad de la aplicación móvil.',
    'txt_42': 'Creé un Servicio de Notificaciones integrando Firebase Cloud Messaging para notificaciones basadas en eventos.',
    'txt_43': 'Diseñé un Servicio de Contenido para mostrar datos de una base de datos MySQL y un Servicio de Información integrado con PeopleSoft usando Oracle SQL.',
    'txt_44': 'BigData/HPC Lab CTIC-UNI',
    'txt_45': 'IOT Software Developer',
    'txt_46': 'Desarrollé un dispositivo Raspberry Pi para la gestión del transporte público, centrándome en el seguimiento GPS y el control de pasajeros.',
    'txt_47': 'Implementé software en Python multihilo para un procesamiento eficiente de datos GPS y comunicación con el backend.',
    'txt_48': 'Trabajo Destacado',
    'txt_49': 'Proyectos Personales',
    'txt_50': 'Desktop App',
    'txt_51': '360 Video Player',
    'txt_52': '360 Video Player es un reproductor de video local para video 360. Simplemente arrastra tu archivo de video al reproductor para sumergirte instantáneamente en una experiencia de 360 grados, todo desde la comodidad de tu propio dispositivo.',
    'txt_53': 'Aplicación Web',
    'txt_54': 'YT-no-cookie',
    'txt_55': 'YT-No-Cookie Viewer es una interfaz web minimalista diseñada para ayudarte a ver videos de YouTube con menos distracciones.',
    'txt_56': 'Desktop App',
    'txt_57': 'SpaceGrid',
    'txt_58': 'Juego en OpenGL/C++ donde controlas una nave espacial que se mueve en una cuadrícula!',
}

link_variables = {
    'link_1': 'index.html',
    'link_2': '#home',
    'link_3': '#about',
    'link_4': '#resume',
    'link_5': '#portfolio',
    'link_6': 'https://www.linkedin.com/in/jes%C3%BAs-andr%C3%A9s-torrej%C3%B3n-le%C3%B3n-511351190/',
    'link_7': 'https://github.com/thehancode',
    'link_8': 'https://x.com/jesucode',
    'link_9': 'index.html',
    'link_10': 'index.html',
    'link_11': '#home',
    'link_12': '#about',
    'link_13': '#resume',
    'link_14': '#portfolio',
    'link_15': 'https://www.linkedin.com/in/jes%C3%BAs-andr%C3%A9s-torrej%C3%B3n-le%C3%B3n-511351190/',
    'link_16': 'https://github.com/thehancode',
    'link_17': 'https://x.com/jesucode',
    'link_18': 'https://github.com/thehancode/360-video-player',
    'link_19': 'https://github.com/thehancode/360-video-player',
    'link_20': 'https://github.com/thehancode/360-video-player',
    'link_21': '#',
    'link_22': 'https://github.com/thehancode/no-cookie-viewer',
    'link_23': 'https://github.com/thehancode/no-cookie-viewer',
    'link_24': 'https://github.com/thehancode/no-cookie-viewer',
    'link_25': '#',
    'link_26': 'https://github.com/thehancode/SpaceGrid',
    'link_27': 'https://github.com/thehancode/SpaceGrid',
    'link_28': 'https://github.com/thehancode/SpaceGrid',
}

image_variables = {
    'img_1': 'assets/images/logo/logo-06.png',
    'img_2': 'assets/images/logo/logo.png',
    'img_3': 'assets/images/logo/logos-circle.png',
    'img_4': 'assets/images/slider/banner-06.png',
    'img_5': 'assets/images/portfolio/portfolio-01.gif',
    'img_6': 'assets/images/portfolio/portfolio-02.jpg',
    'img_7': 'assets/images/portfolio/portfolio-03.png',
}

links_variables = {
    'links_1': 'assets/images/favicon.ico',
    'links_2': 'assets/css/vendor/bootstrap.min.css',
    'links_3': 'assets/css/vendor/slick.css',
    'links_4': 'assets/css/vendor/slick-theme.css',
    'links_5': 'assets/css/vendor/aos.css',
    'links_6': 'assets/css/plugins/feature.css',
    'links_7': 'assets/css/style.css',
    'links_8': 'style.css',
}

script_variables = {
    'script_1': 'assets/js/vendor/jquery.js',
    'script_2': 'assets/js/vendor/modernizer.min.js',
    'script_3': 'assets/js/vendor/feather.min.js',
    'script_4': 'assets/js/vendor/slick.min.js',
    'script_5': 'assets/js/vendor/bootstrap.js',
    'script_6': 'assets/js/vendor/text-type.js',
    'script_7': 'assets/js/vendor/wow.js',
    'script_8': 'assets/js/vendor/aos.js',
    'script_9': 'assets/js/vendor/particles.js',
    'script_10': 'assets/js/main.js',
    'script_11': 'script.js',
}

